apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: 5

  selector:
    matchLabels:
      app: flask

  template:

    metadata:
      labels:
        app: flask

    spec:

      containers:

      - name: flask-container
        image: prithvia24/flask-app:6
        imagePullPolicy: Always

        ports:
        - containerPort: 8000

