name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python
        run: python --version

      - name: Build Docker Image
        run: |
          docker build -t prithvia24/flask-app:${{ github.run_number }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag prithvia24/flask-app:${{ github.run_number }} prithvia24/flask-app:latest
          docker push prithvia24/flask-app:${{ github.run_number }}
          docker push prithvia24/flask-app:latest